import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Creche from 'App/Models/Creche'

export default class extends BaseSeeder {
  public async run() {
    await Creche.createMany([
      {
        nom: 'Rêverie',
        adresse: 'Rue Francisco Ferrer 19 boite 3',
        gsm: ' ',
        ville: '6181 Gouy-Lez-Piéton',
        nombreCaisseLingeS: 1,
        nombreCaisseLingeM: 3,
        nombreCaisseLingeL: 1,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 10,
        nombreCaisseGant: 2,
        tourneeId: 1,
      },
      {
        nom: 'Les ptits loups',
        adresse: 'Rue de la Vielle Place 51',
        gsm: '',
        ville: '6001 Marcinelle',
        nombreCaisseLingeS: 0,
        nombreCaisseLingeM: 3,
        nombreCaisseLingeL: 1,
        nombreCaisseInsert: 0,
        nombreCaisseSacPoubelle: 6,
        nombreCaisseGant: 0,
        tourneeId: 1,
      },
      {
        nom: 'L\'arbre à cabane',
        adresse: 'Chaussée de Nivelles 212',
        gsm: ' ',
        ville: '6041 Gosselies',
        nombreCaisseLingeS: 1,
        nombreCaisseLingeM: 2,
        nombreCaisseLingeL: 1,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 8,
        nombreCaisseGant: 0,
        tourneeId: 1,
      },
      {
        nom: 'Les lutins',
        adresse: 'Rue de Tamines 18',
        gsm: ' ',
        ville: '6224 Wanfercée-Baulet',
        nombreCaisseLingeS: 1,
        nombreCaisseLingeM: 5,
        nombreCaisseLingeL: 2,
        nombreCaisseInsert: 2,
        nombreCaisseSacPoubelle: 12,
        nombreCaisseGant: 1,
        tourneeId: 1,
      },
      {
        nom: 'Les Tiffins',
        adresse: 'Rue des Combattants, 59',
        gsm: ' ',
        ville: '1310 La Hulpe',
        nombreCaisseLingeS: 1,
        nombreCaisseLingeM: 3,
        nombreCaisseLingeL: 2,
        nombreCaisseInsert: 2,
        nombreCaisseSacPoubelle: 12,
        nombreCaisseGant: 0,
        tourneeId: 1,
      },
      {
        nom: 'Cardinal Mercier',
        adresse: 'Rue Souveraine 48',
        gsm: ' ',
        ville: '1050 Bruxelles',
        nombreCaisseLingeS: 0.5,
        nombreCaisseLingeM: 5,
        nombreCaisseLingeL: 1,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 14,
        nombreCaisseGant: 0,
        tourneeId: 1,
      },
      {
        nom: 'Saint Joseph',
        adresse: 'Chaussée de Boisfort 40',
        gsm: ' ',
        ville: '1050 Ixelles',
        nombreCaisseLingeS: 1,
        nombreCaisseLingeM: 3,
        nombreCaisseLingeL: 1.5,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 14,
        nombreCaisseGant: 0,
        tourneeId: 1,
      },
      {
        nom: 'MMI',
        adresse: 'Dorpsstraat 76',
        gsm: ' ',
        ville: '7850 Edingen',
        nombreCaisseLingeS: 1,
        nombreCaisseLingeM: 1.5,
        nombreCaisseLingeL: 0.5,
        nombreCaisseInsert: 0.5,
        nombreCaisseSacPoubelle: 8,
        nombreCaisseGant: 0,
        tourneeId: 2,
      },

      {
        nom: 'IRSIA',
        adresse: 'Place de Pâturages, 41 ',
        gsm: ' ',
        ville: '7340 Colfontaine',
        nombreCaisseLingeS: 2,
        nombreCaisseLingeM: 6,
        nombreCaisseLingeL: 1.5,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 35,
        nombreCaisseGant: 0,
        tourneeId: 2,
      },
      {
        nom: 'Les Poussins',
        adresse: 'Av. Ducpétiaux 16',
        gsm: ' ',
        ville: '1060 Saint-Gilles',
        nombreCaisseLingeS: 0,
        nombreCaisseLingeM: 1,
        nombreCaisseLingeL: 0.5,
        nombreCaisseInsert: 0,
        nombreCaisseSacPoubelle: 4,
        nombreCaisseGant: 0,
        tourneeId: 1,
      },
      {
        nom: 'Royaume',
        adresse: 'Chau. d\'Asse 130',
        gsm: ' ',
        ville: '7850 Enghien',
        nombreCaisseLingeS: 1,
        nombreCaisseLingeM: 3,
        nombreCaisseLingeL: 0.5,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 6,
        nombreCaisseGant: 0,
        tourneeId: 2,
      },
      {
        nom: 'Gratty',
        adresse: 'Place communale 17',
        gsm: ' ',
        ville: '7830 Silly',
        nombreCaisseLingeS: 0,
        nombreCaisseLingeM: 2,
        nombreCaisseLingeL: 0,
        nombreCaisseInsert: 0,
        nombreCaisseSacPoubelle: 6,
        nombreCaisseGant: 0,
        tourneeId: 2,
      },
      {
        nom: 'Boulous',
        adresse: 'Rue de la Coquiane 61',
        gsm: ' ',
        ville: '7850 Petit-Enghien',
        nombreCaisseLingeS: 0.5,
        nombreCaisseLingeM: 2,
        nombreCaisseLingeL: 0.5,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 8,
        nombreCaisseGant: 0,
        tourneeId: 2,
      },
      {
        nom: 'creche1',
        adresse: 'Rue d  Cquine 61',
        gsm: ' ',
        ville: '7850 Petit-Engien',
        nombreCaisseLingeS: 0.5,
        nombreCaisseLingeM: 2,
        nombreCaisseLingeL: 0.5,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 8,
        nombreCaisseGant: 0,
      },
      {
        nom: 'creche2',
        adresse: 'Place de Pâtures, 41 ',
        gsm: ' ',
        ville: '7340 Colfontine',
        nombreCaisseLingeS: 2,
        nombreCaisseLingeM: 6,
        nombreCaisseLingeL: 1.5,
        nombreCaisseInsert: 1,
        nombreCaisseSacPoubelle: 35,
        nombreCaisseGant: 0,
      }

    ])
  }
}
