@baseUrl = http://localhost:3333

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"admin@hotmail.com",
    "password":"71password"
}
### register livreur with admin token
POST {{baseUrl}}/auth/register 
Content-type: application/json
Authorization: Bearer Mw.Z_rqqPK-5UOn1KCBdMTk5BP6heJMYeVGKvO_lCL26xu-Vfj3r9wkx2GGJXmN

{
    "email": "livreur1@hotmail.com",
    "password": "livreur1"
}

### login livreur
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"livreur1@hotmail.com",
    "password":"livreur1"
}

### register livreur with user token (403)
POST {{baseUrl}}/auth/register 
Content-type: application/json
Authorization: Bearer NQ.8Ossg8SiJVyRaG9SxNJHOPOS5FRz0CBXq8zPZ_4roR_iAHgF_zjXfIEA0tek

{
    "email": "livreur1@hotmail.com",
    "password": "livreur1"
}



// ****************************Badrequest/conflit/notfoundtest*/////////////////////////// */

### 
POST {{baseUrl}}/auth/register 
Content-type: application/json
Authorization: Bearer MjE.B8HIYIDAOV01-EvfozO5ZntdvpUrASROH9Px2AMNXzwIyFxLSWsnQg7WWBay

{
    "ee": "livreur1@hotmail.com",
    "paword": "livreur1"
}

### 
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "eail":"livreur1@hotmail.com",
    "passwrd":"livreur1"
}