@baseUrl = https://pfe-2023-backend-prod.azurewebsites.net
### login admin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "nom":"maximilien",
    "password":"71password"
}

### login livreur
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "nom":"livreur1",
    "password":"livreur1"
}

### register livreur with admin token
POST {{baseUrl}}/auth/register 
Content-type: application/json
Authorization: Bearer MQ.y1wCgWiVFg9Bbf_3VIyj7nKwMLuzrMCinz5yKbWqkfPWJQeOOZa9B2nuGr_U

{
    "nom": "hahatudoisecriretoutcadansleloginpourteconnecter3",
    "password": "livreur2"
}

### register same livreur with admin token
POST {{baseUrl}}/auth/register 
Content-type: application/json
Authorization: Bearer MQ.y1wCgWiVFg9Bbf_3VIyj7nKwMLuzrMCinz5yKbWqkfPWJQeOOZa9B2nuGr_U

{
    "nom": "hahatudoisecriretoutcadansleloginpourteconnecter3",
    "password": "livreur2"
}

### register livreur with user token (403)
POST {{baseUrl}}/auth/register 
Content-type: application/json
Authorization: Bearer Mg.AQ1QFjKTND98QLsfCCKr1zmjRYN6t2mYL7BUNg3PUBIhXWxICmKEyf5N-Ej1

{
    "nom": "livreur1@hotmail.com",
    "password": "livreur1"
}

### Change user password with user token
POST {{baseUrl}}/auth/updatePassword 
Content-type: application/json
Authorization: Bearer Mg.AQ1QFjKTND98QLsfCCKr1zmjRYN6t2mYL7BUNg3PUBIhXWxICmKEyf5N-Ej1

{
    "idUser": "2",
    "password": "livreur2"
}

### Change user password with admin token
POST {{baseUrl}}/auth/updatePassword 
Content-type: application/json
Authorization: Bearer MQ.y1wCgWiVFg9Bbf_3VIyj7nKwMLuzrMCinz5yKbWqkfPWJQeOOZa9B2nuGr_U

{
    "idUser": "2",
    "password": "livreur2"
}


### try to connect with old password
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "nom":"hahatudoisecriretoutcadansleloginpourteconnecter2",
    "password":"livreur1"
}

### try to connect with new password
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "nom":"hahatudoisecriretoutcadansleloginpourteconnecter2",
    "password":"livreur2"
}

### reset password admin
GET {{baseUrl}}/auth/resetPasswordAdmin
// ****************************Badrequest/conflit/notfoundtest*/////////////////////////// */

### 
POST {{baseUrl}}/auth/register 
Content-type: application/json
Authorization: Bearer MjE.B8HIYIDAOV01-EvfozO5ZntdvpUrASROH9Px2AMNXzwIyFxLSWsnQg7WWBay

{
    "ee": "livreur1@hotmail.com",
    "paword": "livreur1"
}

### 
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "eail":"livreur1@hotmail.com",
    "passwrd":"livreur1"
}

### test resetpassword with a non admin email
POST {{baseUrl}}/auth/resetPasswordAdmin
Content-Type: application/json

{
    "email":"adame.barhdadi@student.vinci.be"
}