@baseUrl = http://localhost:3333

### GET all nursery
GET {{baseUrl}}/creches
Authorization: Bearer Mg.GO0AzL33mhjfdOMqXzCdrlsyosVq-Z06Ab1LcJPRYfAMqHE5HMMzTsKlOZ3M

### Create one nursery
POST {{baseUrl}}/creches
Content-Type: application/json
Authorization: Bearer NQ.EeUNBiacEgQ0RIYtdm-vrAukVwOTPSASKCAomQH9ZKxrvY2eRPsz8Y0LkWcj

{
    "gsm":"",
    "nom":"creche1",
    "adresse":"avenue venue",
    "ville":"bx"
}

### Create one nursery with already existing adresse
POST {{baseUrl}}/creches
Content-Type: application/json
Authorization: Bearer NQ.EeUNBiacEgQ0RIYtdm-vrAukVwOTPSASKCAomQH9ZKxrvY2eRPsz8Y0LkWcj

{
    "gsm":"01",
    "nom":"creche2",
    "adresse":"avenue venue",
    "ville":"lv"
}
### add product quantity to nursery
POST {{baseUrl}}/creches/2
Content-Type: application/json
Authorization: Bearer Mg.GO0AzL33mhjfdOMqXzCdrlsyosVq-Z06Ab1LcJPRYfAMqHE5HMMzTsKlOZ3M

{
    "nombreCaisseLingeS": 4,
    "nombreCaisseLingeM": 0,
    "nombreCaisseLingeL": 5,
    "nombreCaisseInsert": 8,
    "nombreCaisseSacPoubelle": 10,
    "nombreCaisseGant": 7,
    "gsm":"0456"
}

### delete one
DELETE {{baseUrl}}/creche/1
Content-Type: application/json
Authorization: Bearer MQ.oxPdIrYRV-786TERXafS3x4F3ozGoE04748XzF3dm6n7CoruGCA_N-vfz5dt

