@baseUrl = http://localhost:3333

### Create one nursery
POST {{baseUrl}}/creches
Content-Type: application/json
Authorization: Bearer MQ.vAhTRxMSdHOowHcbOlQHVqhmjFCK3KcunpNP1ZxvBg2fcOIFIzDPe2Gu5tgp

{
    "gsm":"01",
    "nom":"nursery1",
    "adresse":"avenue venue"
}

### add product quantity to nursery
POST {{baseUrl}}/creches/5
Content-Type: application/json
Authorization: Bearer MQ.vAhTRxMSdHOowHcbOlQHVqhmjFCK3KcunpNP1ZxvBg2fcOIFIzDPe2Gu5tgp

{
    "nombreCaisseLingeS": 4,
    "nombreCaisseLingeM": 0,
    "nombreCaisseLingeL": 5,
    "nombreCaisseInsert": 8,
    "nombreCaisseSacPoubelle": 10,
    "nombreCaisseGant": 7,
    "gsm":"0456"
}