@baseUrl = http://localhost:3333

### GET all nursery
GET {{baseUrl}}/creches
Authorization: Bearer MTg.QU9VDzH8DVBe0nmiPkvnXNqjjvYi31WHk495kLi7QzzZT7H3qJZNAz2YNqPc

### GET one
GET {{baseUrl}}/creches/5
Authorization: Bearer MTg.QU9VDzH8DVBe0nmiPkvnXNqjjvYi31WHk495kLi7QzzZT7H3qJZNAz2YNqPc

### Create one nursery
POST {{baseUrl}}/creches
Content-Type: application/json
Authorization: Bearer MQ.XaKtc15OUOOPsrMUqMEHR0J2Gi8_E0H8sZnM7duVtfX-PZI_LNuXMNv4qzMT

{
    "gsm":"0488 63 07 93",
    "nom":"creche3",
    "adresse":"Rue de l'aerschot",
    "ville":"Bruxelles"
}

### Create one nursery with already existing adresse
POST {{baseUrl}}/creches
Content-Type: application/json
Authorization: Bearer MzE.aDC06jkCHF9SJwY0z3MAt8krutdnFw5QSbcntQCblx9qLnGsuISfInDBRujz

{

    "nom":"creche2",
    "adresse":"avenue venue",
    "ville":"lv"
}
### add product quantity to nursery
POST {{baseUrl}}/creches/1
Content-Type: application/json
Authorization: Bearer MTY4.lwLgR26NFYVkE5nofSksRQYAkM5HOx8N3eJo9H4RwjJyrDkmK7C6CjHW8fgi

{
    "nombreCaisseLingeS": 10,
    "nombreCaisseLingeM": 15,
    "nombreCaisseLingeL": 50,
    "nombreCaisseInsert": 80,
    "nombreCaisseSacPoubelle": 10,
    "nombreCaisseGant": 7
}

### delete one
DELETE {{baseUrl}}/creche/1
Content-Type: application/json
Authorization: Bearer MQ.oxPdIrYRV-786TERXafS3x4F3ozGoE04748XzF3dm6n7CoruGCA_N-vfz5dt

### delete from tournee
DELETE {{baseUrl}}/creche/fromTournee/1
Content-Type: application/json
Authorization: Bearer MjAy.OE2G_N0PmtjOj_Idf5KDuVKzXcbml0HAOvDieH2Mfes4Ks-DlHP0doo-RlXG