@baseUrl = http://localhost:3333


### Create delivery 
POST {{baseUrl}}/tournees
Content-Type: application/json
Authorization: Bearer MTY5.SG3JtINMEqAwYcfH_XXs5LJeprH2EITVozXYv8bfA4M-pWBSE3oQefYCSNfH

{
    "creches":[1],
    "nom":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}


### Assign delivery already assigned
POST {{baseUrl}}/tournees/assignDelivery
Content-Type: application/json
Authorization: Bearer NQ.aLLW-gGDSfQfIQ5Q8UhcOIwJb2UDfjLskXoQL-ulsI-nkdNflnKk_MgcDlzg

{
    "idDelivery":1,
    "idDeliveryMan":3
}


### get all with user 2 token
GET  {{baseUrl}}/tournees
Authorization: Bearer Mw.e6LH42nwjjRsLB2uS0mqMIWGMsakuRQFM5HOyJjXL3qrnQYph3dL15_1fPHG

### update not assigned delivery 
PUT  {{baseUrl}}/tournees/updateState/1 
Content-Type: application/json
Authorization: Bearer Mg.LeNgXp3R2OP7YTTEOrp0KyoZ4PQSgKAIP_8OBFRnWcrnX6K-GH3ydKnZO0WB

{
    "nombreCaisseGantLivre": 5,
    "nombreCaisseSacPoubelleLivre":5,
    "nombreCaisseInsertLivre": 5,
    "nombreCaisseLingeLLivre": 5,
    "nombreCaisseLingeMLivre": 5,
    "nombreCaisseLingeSLivre": 5
    "nurseryId":
    "deliveryId":
}
### update already delivered delivery
PUT  {{baseUrl}}/tournees/updateState
Content-Type: application/json
Authorization: Bearer Mg.LeNgXp3R2OP7YTTEOrp0KyoZ4PQSgKAIP_8OBFRnWcrnX6K-GH3ydKnZO0WB

{
    "nombreCaisseGantLivre": 5,
    "nombreCaisseSacPoubelleLivre":5,
    "nombreCaisseInsertLivre": 5,
    "nombreCaisseLingeLLivre": 5,
    "nombreCaisseLingeMLivre": 5,
    "nombreCaisseLingeSLivre": 5,
    "nurseryId":
    "deliveryId":
}
### update assigned  delivery
PUT  {{baseUrl}}/tournees/updateState
Content-Type: application/json
Authorization: Bearer Mg.LeNgXp3R2OP7YTTEOrp0KyoZ4PQSgKAIP_8OBFRnWcrnX6K-GH3ydKnZO0WB

{
    "nombreCaisseGantLivre": 5,
    "nombreCaisseSacPoubelleLivre":5,
    "nombreCaisseInsertLivre": 5,
    "nombreCaisseLingeLLivre": 5,
    "nombreCaisseLingeMLivre": 5,
    "nombreCaisseLingeSLivre": 5,
    "nurseryId":
    "deliveryId":
}

### update assigned  delivery but already delivered
PUT  {{baseUrl}}/tournees/updateState/2 
Content-Type: application/json
Authorization: Bearer Ng.4jpRADX67UDl_eNS6Ar7y_yM9dCalXzA9VvOiLxDw62QFhwbZpjoUEWeOPOD

{
    "nombreCaisseGantLivre": 5,
    "nombreCaisseSacPoubelleLivre":5,
    "nombreCaisseInsertLivre": 5,
    "nombreCaisseLingeLLivre": 5,
    "nombreCaisseLingeMLivre": 5,
    "nombreCaisseLingeSLivre": 5,
    "nurseryId":,
    "deliveryId":
}

### update assigned delivery but with non corresponding nursery
PUT  {{baseUrl}}/tournees/updateState/2 
Content-Type: application/json
Authorization: Bearer Ng.4jpRADX67UDl_eNS6Ar7y_yM9dCalXzA9VvOiLxDw62QFhwbZpjoUEWeOPOD

{
    "nombreCaisseGantLivre": 5,
    "nombreCaisseSacPoubelleLivre":5,
    "nombreCaisseInsertLivre": 5,
    "nombreCaisseLingeLLivre": 5,
    "nombreCaisseLingeMLivre": 5,
    "nombreCaisseLingeSLivre": 5,
    "nurseryId":,
    "deliveryId":
}

### DELETE one tournee
DELETE {{baseUrl}}/tournees/1
Authorization: Bearer MTY5.SG3JtINMEqAwYcfH_XXs5LJeprH2EITVozXYv8bfA4M-pWBSE3oQefYCSNfH

