@baseUrl = http://localhost:3333

### get all with admin token
GET  {{baseUrl}}/tournees
Authorization: Bearer MQ.vAhTRxMSdHOowHcbOlQHVqhmjFCK3KcunpNP1ZxvBg2fcOIFIzDPe2Gu5tgp

### get all with user 2 token
GET  {{baseUrl}}/tournees
Authorization: Bearer Mg.EG2WQM4c0flDiHigzQk041UTHphIrN2OsTxFSp89MTEYBO27TUQYNaJrJ8tU

### update not assigned delivery 
PUT  {{baseUrl}}/tournees/updateState/1 
Content-Type: application/json
Authorization: Bearer Mg.LeNgXp3R2OP7YTTEOrp0KyoZ4PQSgKAIP_8OBFRnWcrnX6K-GH3ydKnZO0WB

{
    "nombreCaisseGantLivre": 5,
    "nombreCaisseSacPoubelleLivre":5,
    "nombreCaisseInsertLivre": 5,
    "nombreCaisseLingeLLivre": 5,
    "nombreCaisseLingeMLivre": 5,
    "nombreCaisseLingeSLivre": 5
}

### update assigned  delivery
PUT  {{baseUrl}}/tournees/updateState/2 
Content-Type: application/json
Authorization: Bearer Mg.LeNgXp3R2OP7YTTEOrp0KyoZ4PQSgKAIP_8OBFRnWcrnX6K-GH3ydKnZO0WB

{
    "nombreCaisseGantLivre": 5,
    "nombreCaisseSacPoubelleLivre":5,
    "nombreCaisseInsertLivre": 5,
    "nombreCaisseLingeLLivre": 5,
    "nombreCaisseLingeMLivre": 5,
    "nombreCaisseLingeSLivre": 5
}


### update already delivered delivery
PUT  {{baseUrl}}/tournees/updateState/2 
Content-Type: application/json
Authorization: Bearer Mg.LeNgXp3R2OP7YTTEOrp0KyoZ4PQSgKAIP_8OBFRnWcrnX6K-GH3ydKnZO0WB

{
    "nombreCaisseGantLivre": 5,
    "nombreCaisseSacPoubelleLivre":5,
    "nombreCaisseInsertLivre": 5,
    "nombreCaisseLingeLLivre": 5,
    "nombreCaisseLingeMLivre": 5,
    "nombreCaisseLingeSLivre": 5
}