@baseUrl = http://localhost:3333


### Create delivery 
POST {{baseUrl}}/tournees
Content-Type: application/json
Authorization: Bearer MQ.HuWfNXJWZb4RIowq9FJeb8W_4lhi8h5BOYVBF2Jmn1rs-pQMBRf2C6g2UQCM

{
    "creches":[15,14],
    "nom":"Tournnnn",
    "pourcentageSupplementaire":50
}


### Assign delivery already assigned
POST {{baseUrl}}/tournees/updateOne
Content-Type: application/json
Authorization: Bearer MQ.HuWfNXJWZb4RIowq9FJeb8W_4lhi8h5BOYVBF2Jmn1rs-pQMBRf2C6g2UQCM

{
    "deliveryId":1,
    "nom":"ddzaaaaaaaaaaaaaaa",
    "creches":[1,2,8]

}


### get all with user 2 token
GET  {{baseUrl}}/tournees/1
Authorization: Bearer MTY.4OBLfAhlBr0DVZPYbVyw56UCe77-o0vPT_woTbsRBi-JF70R3JhdraqTWEcD

### update assigned delivery 
POST  {{baseUrl}}/tournees/updateState
Content-Type: application/json
Authorization: Bearer NQ.tx6XfBZoKWE2m0Dt25CYnAmM2bPRwJnDmMbjHImfEEiHtqu1WvAMtygGr_qQ

{
  "nurseryId": 15,
  "nombreCaisseGantLivre": 0,
  "nombreCaisseSacPoubelleLivre": 1,
  "nombreCaisseInsertLivre": 1,
  "nombreCaisseLingeLLivre": 1,
  "nombreCaisseLingeMLivre": 1,
  "nombreCaisseLingeSLivre": 1
}

### update already delivered delivery
POST  {{baseUrl}}/tournees/updateState
Content-Type: application/json
Authorization: Bearer OTk.m56uKNjDp_a0FhEjSg0bh3zx0Hrx7RTVaAR182PuGLaocLhti_n1zEsoSuz8

{
  "nurseryId": 1,
  "deliveryId": 1,
  "nombreCaisseGantLivre": 4,
  "nombreCaisseSacPoubelleLivre": 10,
  "nombreCaisseInsertLivre": 1,
  "nombreCaisseLingeLLivre": 1,
  "nombreCaisseLingeMLivre": 3,
  "nombreCaisseLingeSLivre": 1
}

### update not assigned  delivery
POST  {{baseUrl}}/tournees/updateState
Content-Type: application/json
Authorization: Bearer Mg.LeNgXp3R2OP7YTTEOrp0KyoZ4PQSgKAIP_8OBFRnWcrnX6K-GH3ydKnZO0WB

{
  "nurseryId": 1,
  "deliveryId": 1,
  "nombreCaisseGantLivre": 2,
  "nombreCaisseSacPoubelleLivre": 10,
  "nombreCaisseInsertLivre": 1,
  "nombreCaisseLingeLLivre": 1,
  "nombreCaisseLingeMLivre": 3,
  "nombreCaisseLingeSLivre": 1
}


### update assigned delivery but with non corresponding nursery
POST  {{baseUrl}}/tournees/updateState
Content-Type: application/json
Authorization: Bearer OTk.m56uKNjDp_a0FhEjSg0bh3zx0Hrx7RTVaAR182PuGLaocLhti_n1zEsoSuz8

{
  "nurseryId": 4,
  "deliveryId": 1,
  "nombreCaisseGantLivre": 2,
  "nombreCaisseSacPoubelleLivre": 12,
  "nombreCaisseInsertLivre": 1,
  "nombreCaisseLingeLLivre": 1,
  "nombreCaisseLingeMLivre": 3,
  "nombreCaisseLingeSLivre": 1
}

### update assigned delivery but with not enough extra quantity in stock
POST  {{baseUrl}}/tournees/updateState
Content-Type: application/json
Authorization: Bearer OTk.m56uKNjDp_a0FhEjSg0bh3zx0Hrx7RTVaAR182PuGLaocLhti_n1zEsoSuz8

{
  "nurseryId": 1,
  "deliveryId": 1,
  "nombreCaisseGantLivre": 2,
  "nombreCaisseSacPoubelleLivre": 2,
  "nombreCaisseInsertLivre": 70,
  "nombreCaisseLingeLLivre": 2,
  "nombreCaisseLingeMLivre": 2,
  "nombreCaisseLingeSLivre": 2
}

### DELETE one tournee
DELETE {{baseUrl}}/tournees/12
Authorization: Bearer MQ.HuWfNXJWZb4RIowq9FJeb8W_4lhi8h5BOYVBF2Jmn1rs-pQMBRf2C6g2UQCM

