@baseUrl = http://localhost:3333


### get all users
GET {{baseUrl}}/users/livreurs
Content-Type: application/json
Authorization: Bearer MTE.2Be-WYRov7pp6jBci6NkKvoy3KrT8ufaVYGwH7Lbnj55wEKW_nvN8LwJBxcQ


### get all users with non-admin token
GET {{baseUrl}}/users/livreurs
Content-Type: application/json
Authorization: Bearer MTE.2Be-WYRov7pp6jBci6NkKvoy3KrT8ufaVYGwH7Lbnj55wEKW_nvN8LwJBxc


